[build]
  command = "npm cache clean --force && npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200

[functions]
  directory = "dist"
