[build]
  command = "rm -rf node_modules package-lock.json && npm install --no-package-lock --include=dev && npm install typescript tsup && npx tsup"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "dist"
  included_files = ["dist/index.js"]

[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200
